services:
  - type: web
    name: my-strapi-app
    env: node
    plan: free
    buildCommand: npm install && npm run build  # Убедитесь, что вы установили зависимости перед сборкой
    startCommand: npm run start
    region: oregon
    autoDeploy: true
